#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install -y haproxy

echo 'ENABLED=1' >> /etc/default/haproxy

printf %s "backend app_server
  balance roundrobin
  server 3157-web-01 35.229.49.186:80 check
  server 3157-web-02 35.190.162.166:80 check

frontend lb_server
  bind 0.0.0.0:80
  mode http
  default_backend app_server
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
